import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  EXPENSE_RGB,
  INCOME_RGB,
  PROFIT_RGB,
  REVENUE_RGB,
  formatReportMoney,
} from "@/lib/reportColors";

type Rgb = [number, number, number];

export type BarChartItem = {
  label: string;
  value: number;
  color: Rgb;
};

function businessName() {
  return localStorage.getItem("profit-pilot-business-name") || "Trippo";
}

export function addReportPdfHeader(
  doc: jsPDF,
  title: string,
  subtitle?: string,
  meta?: string,
) {
  const margin = 14;
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(30, 41, 59);
  doc.text(businessName(), margin, 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(51, 65, 85);
  doc.text(title, margin, 24);

  if (subtitle) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(subtitle, margin, 30);
  }

  if (meta) {
    doc.setFontSize(8);
    const metaWidth = doc.getTextWidth(meta);
    doc.text(meta, pageWidth - margin - metaWidth, 24);
  }

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, 34, pageWidth - margin, 34);
}

export function addReportPdfFooter(
  doc: jsPDF,
  pageNum: number,
  totalPages: number,
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const footerY = pageHeight - 12;

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Trippo", margin, footerY);
  doc.text(
    `Page ${pageNum} of ${totalPages} · ${new Date().toLocaleDateString()}`,
    pageWidth - margin,
    footerY,
    { align: "right" },
  );
}

function ensureSpace(doc: jsPDF, y: number, needed: number, onNewPage: () => number): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - 20) {
    doc.addPage();
    return onNewPage();
  }
  return y;
}

export function drawPdfBarChart(
  doc: jsPDF,
  y: number,
  margin: number,
  pageWidth: number,
  title: string,
  items: BarChartItem[],
  onNewPage: () => number,
): number {
  if (items.length === 0) return y;

  const chartItems = items.filter((i) => i.value > 0).slice(0, 8);
  if (chartItems.length === 0) return y;

  const chartHeight = 8 + chartItems.length * 14 + 4;
  y = ensureSpace(doc, y, chartHeight + 10, onNewPage);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59);
  doc.text(title, margin, y);
  y += 8;

  const maxVal = Math.max(...chartItems.map((i) => i.value), 1);
  const barMaxWidth = pageWidth - margin * 2 - 90;

  chartItems.forEach((item) => {
    const barWidth = Math.max(4, (item.value / maxVal) * barMaxWidth);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    const label = item.label.length > 22 ? `${item.label.slice(0, 22)}…` : item.label;
    doc.text(label, margin, y + 4);

    doc.setFillColor(...item.color);
    doc.roundedRect(margin + 72, y - 2, barWidth, 7, 1, 1, "F");

    doc.setFont("helvetica", "bold");
    doc.setTextColor(...item.color);
    doc.text(formatReportMoney(item.value), margin + 76 + barWidth, y + 4);

    y += 14;
  });

  return y + 6;
}

type PdfTableOptions = {
  doc: jsPDF;
  title: string;
  head: string[][];
  body: (string | number)[][];
  y: number;
  margin: number;
  pageWidth: number;
  pageHeight: number;
  onNewPage: () => number;
  incomeColumns?: number[];
  expenseColumns?: number[];
};

export function appendPdfTable({
  doc,
  title,
  head,
  body,
  y,
  margin,
  pageWidth,
  pageHeight,
  onNewPage,
  incomeColumns = [],
  expenseColumns = [],
}: PdfTableOptions): number {
  if (body.length === 0) return y;

  y = ensureSpace(doc, y, 24, onNewPage);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59);
  doc.text(title, margin, y);
  y += 6;

  const columnStyles: Record<number, { textColor?: Rgb; fontStyle?: string }> = {};
  incomeColumns.forEach((col) => {
    columnStyles[col] = { textColor: INCOME_RGB, fontStyle: "bold" };
  });
  expenseColumns.forEach((col) => {
    columnStyles[col] = { textColor: EXPENSE_RGB, fontStyle: "bold" };
  });

  autoTable(doc, {
    startY: y,
    head,
    body,
    theme: "plain",
    headStyles: {
      fillColor: [248, 250, 252],
      textColor: [51, 65, 85],
      fontStyle: "bold",
      lineWidth: 0.1,
      lineColor: [226, 232, 240],
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      lineWidth: 0.1,
      lineColor: [241, 245, 249],
    },
    alternateRowStyles: { fillColor: [252, 252, 253] },
    columnStyles,
    styles: { fontSize: 9, cellPadding: 3 },
    margin: { left: margin, right: margin },
    didDrawPage: () => {
      onNewPage();
    },
  });

  return (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
}

function finalizePdf(doc: jsPDF, filename: string) {
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addReportPdfFooter(doc, i, totalPages);
  }
  doc.save(filename);
}

export type PlatformReportPdfInput = {
  reportType: string;
  dateRangeLabel: string;
  barberPeriod: string;
  totalLabel: string;
  totalRevenue: number;
  totalExpenses: number;
  totalProfit: number;
  totalQuantity: number;
  bestSelling: { product: string; quantity: number };
  platformStats: {
    salesRevenue: number;
    salesProfit: number;
    expenses: number;
    netFromSales: number;
    income: number;
    payroll: number;
    billsPaid: number;
    taxesPaid: number;
    invoicesPaid: number;
    bankDeposits: number;
    loanBalance: number;
    inventoryValue: number;
  };
  salesExpensesByPeriod: Array<{
    label: string;
    salesRevenue: number;
    expenses: number;
    salesProfit: number;
  }>;
  salesExpensesPeriodTotals: { revenue: number; expenses: number; net: number };
  salesByProduct: Array<{ product: string; quantity: number; revenue: number }>;
  workerBreakdown: Array<{ barber: string; services: number; revenue: number; topServices: string[] }>;
  financeIncomeRows: Array<{ title: string; date: string; amount: number }>;
  financePayrollRows: Array<{ title: string; date: string; amount: number; status?: string }>;
  financeBillRows: Array<{ title: string; date: string; amount: number; status?: string }>;
  financeTaxRows: Array<{ title: string; date: string; amount: number; status?: string }>;
  financeInvoiceRows: Array<{ title: string; date: string; amount: number; status?: string }>;
  inventoryProductRows: Array<{ name: string; category: string; stock: number; inventoryValue: number }>;
};

export function exportPlatformReportPdf(data: PlatformReportPdfInput) {
  const doc = new jsPDF();
  const margin = 14;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generated = `Generated: ${new Date().toLocaleString()}`;

  const refreshHeader = () => {
    addReportPdfHeader(
      doc,
      "Platform Report",
      `${data.reportType} · ${data.dateRangeLabel}`,
      generated,
    );
    return 40;
  };

  let y = refreshHeader();

  y = drawPdfBarChart(
    doc,
    y,
    margin,
    pageWidth,
    "Income vs Expenses Overview",
    [
      { label: "Sales Revenue", value: data.platformStats.salesRevenue, color: REVENUE_RGB },
      { label: "Income", value: data.platformStats.income, color: INCOME_RGB },
      { label: "Expenses", value: data.platformStats.expenses, color: EXPENSE_RGB },
      { label: "Payroll", value: data.platformStats.payroll, color: EXPENSE_RGB },
      { label: "Bills Paid", value: data.platformStats.billsPaid, color: EXPENSE_RGB },
    ],
    refreshHeader,
  );

  y = appendPdfTable({
    doc,
    title: "Summary",
    head: [["Metric", "Value"]],
    body: [
      ["Sales Revenue", formatReportMoney(data.totalRevenue)],
      ["Total Expenses", formatReportMoney(data.totalExpenses)],
      ["Net Profit", formatReportMoney(data.totalProfit)],
      ["Finance Income", formatReportMoney(data.platformStats.income)],
      ["Quantity Sold", String(data.totalQuantity)],
      ["Best Seller", data.bestSelling.product],
    ],
    y,
    margin,
    pageWidth,
    pageHeight,
    onNewPage: refreshHeader,
    incomeColumns: [1],
    expenseColumns: [],
  });

  const periodChartItems: BarChartItem[] = data.salesExpensesByPeriod.slice(0, 6).map((row) => ({
    label: row.label,
    value: row.salesRevenue,
    color: REVENUE_RGB,
  }));
  const periodExpenseItems: BarChartItem[] = data.salesExpensesByPeriod.slice(0, 6).map((row) => ({
    label: row.label,
    value: row.expenses,
    color: EXPENSE_RGB,
  }));

  y = drawPdfBarChart(doc, y, margin, pageWidth, "Revenue by Period", periodChartItems, refreshHeader);
  y = drawPdfBarChart(doc, y, margin, pageWidth, "Expenses by Period", periodExpenseItems, refreshHeader);

  const salesExpensesRows = data.salesExpensesByPeriod.map((row) => {
    const net = (row.salesProfit || 0) - (row.expenses || 0);
    return [row.label, formatReportMoney(row.salesRevenue), formatReportMoney(row.expenses), formatReportMoney(net)];
  });
  if (salesExpensesRows.length > 0) {
    salesExpensesRows.push([
      data.totalLabel,
      formatReportMoney(data.salesExpensesPeriodTotals.revenue),
      formatReportMoney(data.salesExpensesPeriodTotals.expenses),
      formatReportMoney(data.salesExpensesPeriodTotals.net),
    ]);
  }

  y = appendPdfTable({
    doc,
    title: "Sales & Expenses",
    head: [["Period", "Revenue", "Expenses", "Net"]],
    body: salesExpensesRows,
    y,
    margin,
    pageWidth,
    pageHeight,
    onNewPage: refreshHeader,
    incomeColumns: [1, 3],
    expenseColumns: [2],
  });

  y = appendPdfTable({
    doc,
    title: "Top Products / Services",
    head: [["Name", "Qty", "Revenue"]],
    body: data.salesByProduct.slice(0, 15).map((r) => [r.product, r.quantity, formatReportMoney(r.revenue)]),
    y,
    margin,
    pageWidth,
    pageHeight,
    onNewPage: refreshHeader,
    incomeColumns: [2],
  });

  y = appendPdfTable({
    doc,
    title: `Worker Performance (${data.barberPeriod})`,
    head: [["Worker", "Services", "Top Services", "Revenue"]],
    body: data.workerBreakdown.map((r) => [
      r.barber,
      r.services,
      r.topServices.join(", ") || "—",
      formatReportMoney(r.revenue),
    ]),
    y,
    margin,
    pageWidth,
    pageHeight,
    onNewPage: refreshHeader,
    incomeColumns: [3],
  });

  y = appendPdfTable({
    doc,
    title: "Finance — Income",
    head: [["Title", "Date", "Amount"]],
    body: data.financeIncomeRows.map((r) => [r.title, r.date, formatReportMoney(r.amount)]),
    y,
    margin,
    pageWidth,
    pageHeight,
    onNewPage: refreshHeader,
    incomeColumns: [2],
  });

  y = appendPdfTable({
    doc,
    title: "Finance — Payroll & Bills",
    head: [["Title", "Date", "Status", "Amount"]],
    body: [
      ...data.financePayrollRows.map((r) => [r.title, r.date, r.status || "—", formatReportMoney(r.amount)]),
      ...data.financeBillRows.map((r) => [r.title, r.date, r.status || "—", formatReportMoney(r.amount)]),
    ],
    y,
    margin,
    pageWidth,
    pageHeight,
    onNewPage: refreshHeader,
    expenseColumns: [3],
  });

  appendPdfTable({
    doc,
    title: "Inventory (Top 30)",
    head: [["Product", "Category", "Stock", "Value"]],
    body: data.inventoryProductRows.slice(0, 30).map((r) => [
      r.name,
      r.category || "—",
      r.stock,
      formatReportMoney(r.inventoryValue),
    ]),
    y,
    margin,
    pageWidth,
    pageHeight,
    onNewPage: refreshHeader,
  });

  finalizePdf(doc, `Trippo_Report_${data.reportType}_${new Date().toISOString().slice(0, 10)}.pdf`);
}

export type ProfitLossPdfData = {
  revenue: number;
  totalExpenses: number;
  netProfit: number;
  payroll: number;
  revenueLines?: Array<{ label: string; amount: number }>;
  expenseLines?: Array<{ label: string; amount: number }>;
};

export type BalanceSheetPdfData = {
  assets: { cashAndBank: number; accountsReceivable: number; inventoryValue: number; total: number };
  liabilities: { accountsPayable: number; loanLiabilities: number; total: number };
  equity: number;
};

export type CashFlowPdfData = {
  operating: { cashIn: number; cashOut: number; net: number };
  financing: { deposits: number };
  netChangeInCash: number;
};

export function exportFinancialStatementPdf(
  type: "profitLoss" | "balanceSheet" | "cashFlow",
  statement: ProfitLossPdfData | BalanceSheetPdfData | CashFlowPdfData,
  meta: { startDate?: string; endDate?: string; asOfDate?: string },
) {
  const doc = new jsPDF();
  const margin = 14;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generated = `Generated: ${new Date().toLocaleString()}`;

  const titles = {
    profitLoss: "Profit & Loss Statement",
    balanceSheet: "Balance Sheet",
    cashFlow: "Cash Flow Statement",
  };

  const subtitle =
    type === "balanceSheet"
      ? `As of ${meta.asOfDate || "—"}`
      : `${meta.startDate || "—"} to ${meta.endDate || "—"}`;

  const refreshHeader = () => {
    addReportPdfHeader(doc, titles[type], subtitle, generated);
    return 40;
  };

  let y = refreshHeader();

  if (type === "profitLoss") {
    const pl = statement as ProfitLossPdfData;
    y = drawPdfBarChart(doc, y, margin, pageWidth, "Revenue vs Expenses", [
      { label: "Total Revenue", value: pl.revenue, color: INCOME_RGB },
      { label: "Total Expenses", value: pl.totalExpenses, color: EXPENSE_RGB },
      {
        label: "Net Profit",
        value: Math.abs(pl.netProfit),
        color: pl.netProfit >= 0 ? PROFIT_RGB : EXPENSE_RGB,
      },
    ], refreshHeader);

    const revenueBody: (string | number)[][] = [];
    (pl.revenueLines || []).forEach((line) => {
      revenueBody.push([line.label, formatReportMoney(line.amount)]);
    });
    revenueBody.push(["Total Revenue", formatReportMoney(pl.revenue)]);

    y = appendPdfTable({
      doc,
      title: "Revenue Detail",
      head: [["Line Item", "Amount"]],
      body: revenueBody,
      y,
      margin,
      pageWidth,
      pageHeight,
      onNewPage: refreshHeader,
      incomeColumns: [1],
    });

    const expenseBody: (string | number)[][] = [];
    (pl.expenseLines || []).forEach((line) => {
      expenseBody.push([line.label, formatReportMoney(line.amount)]);
    });
    expenseBody.push(["Payroll", formatReportMoney(pl.payroll)]);
    expenseBody.push(["Total Expenses", formatReportMoney(pl.totalExpenses)]);

    y = appendPdfTable({
      doc,
      title: "Expense Detail",
      head: [["Line Item", "Amount"]],
      body: expenseBody,
      y,
      margin,
      pageWidth,
      pageHeight,
      onNewPage: refreshHeader,
      expenseColumns: [1],
    });

    appendPdfTable({
      doc,
      title: "Net Result",
      head: [["Line Item", "Amount"]],
      body: [["Net Profit", formatReportMoney(pl.netProfit)]],
      y,
      margin,
      pageWidth,
      pageHeight,
      onNewPage: refreshHeader,
      incomeColumns: pl.netProfit >= 0 ? [1] : [],
      expenseColumns: pl.netProfit < 0 ? [1] : [],
    });
  }

  if (type === "balanceSheet") {
    const bs = statement as BalanceSheetPdfData;
    y = drawPdfBarChart(doc, y, margin, pageWidth, "Assets vs Liabilities", [
      { label: "Total Assets", value: bs.assets.total, color: REVENUE_RGB },
      { label: "Total Liabilities", value: bs.liabilities.total, color: EXPENSE_RGB },
      { label: "Equity", value: bs.equity, color: INCOME_RGB },
    ], refreshHeader);

    y = appendPdfTable({
      doc,
      title: "Assets",
      head: [["Item", "Amount"]],
      body: [
        ["Cash & Bank", formatReportMoney(bs.assets.cashAndBank)],
        ["Accounts Receivable", formatReportMoney(bs.assets.accountsReceivable)],
        ["Inventory Value", formatReportMoney(bs.assets.inventoryValue)],
        ["Total Assets", formatReportMoney(bs.assets.total)],
      ],
      y,
      margin,
      pageWidth,
      pageHeight,
      onNewPage: refreshHeader,
      incomeColumns: [1],
    });

    appendPdfTable({
      doc,
      title: "Liabilities & Equity",
      head: [["Item", "Amount"]],
      body: [
        ["Accounts Payable", formatReportMoney(bs.liabilities.accountsPayable)],
        ["Loan Liabilities", formatReportMoney(bs.liabilities.loanLiabilities)],
        ["Total Liabilities", formatReportMoney(bs.liabilities.total)],
        ["Equity", formatReportMoney(bs.equity)],
      ],
      y,
      margin,
      pageWidth,
      pageHeight,
      onNewPage: refreshHeader,
      expenseColumns: [1],
    });
  }

  if (type === "cashFlow") {
    const cf = statement as CashFlowPdfData;
    y = drawPdfBarChart(doc, y, margin, pageWidth, "Cash Flow", [
      { label: "Operating Cash In", value: cf.operating.cashIn, color: INCOME_RGB },
      { label: "Operating Cash Out", value: cf.operating.cashOut, color: EXPENSE_RGB },
      { label: "Financing Deposits", value: cf.financing.deposits, color: REVENUE_RGB },
      {
        label: "Net Change",
        value: Math.abs(cf.netChangeInCash),
        color: cf.netChangeInCash >= 0 ? PROFIT_RGB : EXPENSE_RGB,
      },
    ], refreshHeader);

    appendPdfTable({
      doc,
      title: "Cash Flow Detail",
      head: [["Item", "Amount"]],
      body: [
        ["Operating Cash In", formatReportMoney(cf.operating.cashIn)],
        ["Operating Cash Out", formatReportMoney(cf.operating.cashOut)],
        ["Net Operating Cash", formatReportMoney(cf.operating.net)],
        ["Financing Deposits", formatReportMoney(cf.financing.deposits)],
        ["Net Change in Cash", formatReportMoney(cf.netChangeInCash)],
      ],
      y,
      margin,
      pageWidth,
      pageHeight,
      onNewPage: refreshHeader,
      incomeColumns: [1],
      expenseColumns: [],
    });
  }

  finalizePdf(
    doc,
    `Trippo_${type}_${new Date().toISOString().slice(0, 10)}.pdf`,
  );
}
